docs/01_overview/01_platform_and_toolchain.md
docs/01_overview/02_core_concepts.md
docs/01_overview/index.md
docs/02_getting-started/02_development-environment/05_create-development-wallet.md
docs/02_getting-started/03_smart-contract-development/01_hello-world.md
docs/02_getting-started/03_smart-contract-development/02_deploy-issue-and-transfer-tokens.md
docs/02_getting-started/03_smart-contract-development/03_understanding-ABI-files.md
docs/03_tutorials/10_bios-boot-sequence.md
docs/03_tutorials/20_tic-tac-toe-game-contract.md

https://github.com/eosnetworkfoundation/welcome/commit/4adfb07e53d2898694a53e0e7be0a42b5e3c8c17

port the following Eric's change

---

glossary.md

Update glossary with curated version

---

docs/02_getting-started/03_smart-contract-development/01_hello-world.md
docs/02_getting-started/03_smart-contract-development/02_deploy-issue-and-transfer-tokens.md
docs/02_getting-started/03_smart-contract-development/03_understanding-ABI-files.md
docs/02_getting-started/03_smart-contract-development/04_data-persistence.md
docs/02_getting-started/03_smart-contract-development/05_secondary-indices.md
docs/02_getting-started/03_smart-contract-development/06_adding-inline-actions.md
docs/02_getting-started/03_smart-contract-development/07_inline-action-to-external-contract.md
docs/02_getting-started/03_smart-contract-development/08_linking-custom-permission.md
docs/02_getting-started/03_smart-contract-development/10_payable_actions.md
docs/03_tutorials/10_bios-boot-sequence.md
docs/03_tutorials/20_tic-tac-toe-game-contract.md
docs/03_tutorials/20_tic-tac-toe-game-smart-contract-single-node.md
docs/04_protocol/02_transactions_protocol.md

fixes for smart contract development section in welcome for ENF
part of this bigger item: https://github.com/orgs/eosnetworkfoundation/projects/18/views/1

Fixes for smart contract development section in welcome for ENF

---

docs/03_tutorials/10_bios-boot-sequence.md

Resolves eosnetworkfoundation/devrel#118

Fix small typo in bios boot tutorial

---

docs/02_getting-started/02_development-environment/06_start-your-node-setup.md

Remove deprecated flags from nodeos command

Remove deprecated flags from `nodeos` command

---

docs/40_resources/10_protocol/03_network_peer_protocol.md

resolves #45 
Fixed broken image, can't get `feature-sidebar` docusaursus builds working without this update.

fixed p2p-node-peer-sync img path

---

docs/50_eos-evm/10_getting-started.md
docs/50_eos-evm/20_eos-evm-network/20_connect-metamask.md
docs/50_eos-evm/20_eos-evm-network/30_resources.md
docs/50_eos-evm/20_eos-evm-network/index.md
docs/50_eos-evm/30_developer-guide/10_architecture.md
docs/50_eos-evm/30_developer-guide/20_compatibility/20_json-rpc-compatibility.md
docs/50_eos-evm/30_developer-guide/30_deploy-local-nodes.md
docs/50_eos-evm/30_developer-guide/40_smart-contracts.md
docs/50_eos-evm/30_developer-guide/50_develop-eos-evm-smart-contracts-with-remix.md
docs/50_eos-evm/30_developer-guide/index.md

fixes https://github.com/eosnetworkfoundation/devrel/issues/177
Go through the EVM docs and replace the term "Trust" with "EOS"

devrel #177 trust -> eos evm

---

docs/20_smart-contracts/30_tutorials/55_tic-tac-toe-game-contract.md
docs/20_smart-contracts/30_tutorials/55_tic-tac-toe-game-smart-contract-single-node.md
docs/20_smart-contracts/30_tutorials/index.md
docs/40_node-operation/20_tutorials/10_bios-boot-sequence.md

Partially resolves eosnetworkfoundation/devrel#204

Fix broken links in docs repo

---

docs/index.md

Resolves eosnetworkfoundation/devrel#197

Update welcome page with intro and roles

---

docs/50_eos-evm/10_getting-started.md
docs/50_eos-evm/20_eos-evm-network/index.md
docs/50_eos-evm/30_developer-guide/40_smart-contracts.md
docs/50_eos-evm/index.md

fix docs#64 eos evm for march release

---

docs/50_eos-evm/20_eos-evm-network/20_connect-metamask.md
docs/50_eos-evm/20_eos-evm-network/30_resources.md
docs/50_eos-evm/30_developer-guide/30_deploy-local-nodes.md
docs/50_eos-evm/30_developer-guide/40_smart-contracts.md
docs/50_eos-evm/30_developer-guide/50_develop-eos-evm-smart-contracts-with-remix.md
docs/50_eos-evm/30_developer-guide/60_how_to_verify_a_smart_contract.md

PR for domains rename (March release) V2 (use *evm*)

PR for domains rename (March release) V2 (use *evm*)

---

docs/50_eos-evm/20_eos-evm-network/20_connect-metamask.md
docs/50_eos-evm/20_eos-evm-network/30_resources.md
docs/50_eos-evm/30_developer-guide/40_smart-contracts.md
docs/50_eos-evm/30_developer-guide/50_develop-eos-evm-smart-contracts-with-remix.md
docs/50_eos-evm/30_developer-guide/60_how_to_verify_a_smart_contract.md

Reverts eosnetworkfoundation/docs#72

Revert "add temporary IPs for EVM"

---

docs/50_eos-evm/20_eos-evm-network/20_connect-metamask.md
docs/50_eos-evm/20_eos-evm-network/30_resources.md
docs/50_eos-evm/30_developer-guide/40_smart-contracts.md
docs/50_eos-evm/30_developer-guide/50_develop-eos-evm-smart-contracts-with-remix.md
docs/50_eos-evm/30_developer-guide/60_how_to_verify_a_smart_contract.md

Reverts eosnetworkfoundation/docs#74

Revert "Revert "add temporary IPs for EVM""

---

docs/50_eos-evm/10_getting-started.md

Staging -> Main 2

---

docs/50_eos-evm/30_compatibility/10_evm-compatibility.md

Resolves https://github.com/eosnetworkfoundation/devrel/issues/149
Resolves partially https://github.com/eosnetworkfoundation/devrel/issues/209

Update EVM compatibility section

---

docs/50_eos-evm/20_getting_started/10_connect-metamask.md
docs/50_eos-evm/20_getting_started/30_develop-with-remix.md
docs/50_eos-evm/20_getting_started/40_develop-with-truffle.md
docs/50_eos-evm/20_getting_started/50_develop-with-hardhat.md
docs/50_eos-evm/20_getting_started/60_how_to_verify_a_smart_contract.md
docs/50_eos-evm/50_helpful_links.md

EOS EVM: Prepare urls for mainnet

EOS EVM: Prepare urls for mainnet

---

docs/50_eos-evm/20_getting_started/10_connect-metamask.md
docs/50_eos-evm/20_getting_started/40_develop-with-truffle.md
docs/50_eos-evm/20_getting_started/50_develop-with-hardhat.md

change EOS EVM mainnet port to 17777

change EOS EVM mainnet port to 17777

---

docs/50_eos-evm/30_compatibility/10_evm-compatibility.md

Resolves https://github.com/eosnetworkfoundation/devrel/issues/216

Update EVM compatibility page on SMEs feedback

---

docs/50_eos-evm/30_compatibility/20_json-rpc-compatibility.md

Resolves https://github.com/eosnetworkfoundation/devrel/issues/217

Update JSON-RPC API EVM compatibility list

---

docs/60_protocol-guides/01_consensus_protocol.md
docs/60_protocol-guides/02_transactions_protocol.md
docs/60_protocol-guides/03_network_peer_protocol.md
docs/60_protocol-guides/04_accounts_and_permissions.md

Resolves eosnetworkfoundation/devrel#276

Fix headings in protocol docs to render page nav correctly

---

docs/20_smart-contracts/10_getting-started/10_dune-guide.md

Changes made to capitalization of titles
Changes made to language of titles
Check title for uniqueness

capitalization and title corrections

---

docs/20_smart-contracts/10_getting-started/20_accounts.md

Make capitalization corrections to titles

corrected title capitalization and reviewed format

---

docs/40_node-operation/10_getting-started/10_hardware-requirements.md

#307 add hardware requirements for node operators
resolves https://github.com/orgs/eosnetworkfoundation/projects/18/views/21?pane=issue&itemId=30010045
resolves https://github.com/eosnetworkfoundation/devrel/issues/307

#307 add hardware requirements for node operators

---

native/07_node-operation/10_getting-started/40_peering.md

Resolves https://github.com/eosnetworkfoundation/devrel/issues/340

Improve peering section in node operation journey

---

native/07_node-operation/20_api-node.md

Resolves https://github.com/eosnetworkfoundation/devrel/issues/342

Fix local links after API node guide relocation

---

native/07_node-operation/100_migration-guides/04_upgrade-guide-spring-1-0.md
native/07_node-operation/100_migration-guides/10_switch-to-savanna.md
native/07_node-operation/100_migration-guides/index.md
native/60_advanced-topics/05_managing-finalizer-keys.md

- Added Upgrade Guides for Spring
- Added Guide on switching to Savanna Consensus
- Added Guide on managing Finalizer Keys

Spring Documentation Update

---

native/07_node-operation/100_migration-guides/10_switch-to-savanna.md

fix unresolved merge conflict

---

native/07_node-operation/100_migration-guides/10_switch-to-savanna.md
native/60_advanced-topics/21_managing-finalizer-keys.md

change to hyphen from underscore.

Fix Broken Links in Introduction-Finalizer-Voting

---

native/07_node-operation/100_migration-guides/04_upgrade-guide-spring-1-0.md
native/07_node-operation/100_migration-guides/10_switch-to-savanna.md
native/60_advanced-topics/21_managing-finalizer-keys.md

Spring will require EOS system contracts 3.6

Update System Contracts Expected Version to 3.6

---

native/07_node-operation/100_migration-guides/10_switch-to-savanna.md

Update Protocol Feature List Required for EOS System Contracts v3.6.0

Switch to SVN Required Features
